### ISSUE TITLE
New to REST and TinyRest, need help.

### ISSUE THREAD

**Issue by Mason32NZ** [rflechner/TinyRest#1]
Hi,

Thank your for making this it looks quite simple to use but I fell there is a lack of documentation.
Could you please provide documentation on all the methods available, how to use them, what arguments they take etc. Also does this support authentication in anyway and how could I easily add it to my project?

Looking forward to your reply.

Thanks.

**Comment by Mason32NZ** [comment]
Also, how to you add querys? 
(btw, I am making a C# console application)

**Comment by rflechner** [comment]
Hi,

I have to improve this but you can do:

```
TinyRestServerCSharp.TinyRest.Server()
                .WithLogger(new TinyRestServer.ConsoleLogger())
                .WithHttp()
                .WithPort(8001)
                .WithBasePath("/ApiMocking")
               .OnGetPath("/hello", (request, response) =>
                {
                    var query = request.QueryString.ToDictionary(kv => kv.Key, kv => kv.Value);
                    return "hello " + query["name"];
                })
```
Then you can do call `http://localhost:8001/ApiMocking/hello?name=romain`

Concerning authentication, it's not natively managed but you can do something with functions compostion.

**Comment by Mason32NZ** [comment]
Awesome! Thank you very much for the quick reply. I will give that a go and am looking forward to using TinyRest. I hope you continue to support TinyRest and maintain and add features when possible! :)
